
import { User, Customer, Appointment } from './types';

// CONFIG
export const PASSWORD_MIN_LENGTH = 5;
export const WORKPLACE_COORDS = { latitude: 39.92, longitude: 32.85 };

// ASSETS
export const ASSETS = {
    CNK_LOGO_BASE64: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAAyCAYAAACqNX6DAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF6SURBVHgB7ZqxTsMwEIZfS6sqmBhYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJj8Z/IF5R8rFm7W+98AAAAASUVORK5CYII=',
    BWORKS_LOGO_BASE64: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAAyCAYAAACqNX6DAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAF6SURBVHgB7ZqxTsMwEIZfS6sqmBhYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJiYmJgYmJj8Z/IF5R8rFm7W+98AAAAASUVORK5CYII=',
    LOGIN_BG_CNK_OFFICE: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80'
};

export const COMPANY_INFO = {
    name: 'CNK Kesici Takım',
    email: 'satis@cnkkesicitakim.com.tr',
    website: 'www.cnkkesicitakim.com.tr',
    phone: '+90 312 123 45 67',
    fax: '+90 312 123 45 68',
    taxOffice: 'İvedik',
    taxNumber: '1234567890',
    authorizedPerson: 'Cenk Dikmen'
};

// MOCK DATA FOR SEEDING
// Fix: Added explicit 'id' to DEFAULT_ADMIN to prevent IDBObjectStore errors
export const DEFAULT_ADMIN: User = {
    id: 'admin-id',
    username: 'admin',
    password: '12345',
    role: 'admin',
    name: 'Yönetici',
    jobTitle: 'Sistem Yöneticisi',
    avatar: '',
    employmentStatus: 'Aktif'
};

export const MOCK_CUSTOMERS = [];
export const MOCK_APPOINTMENTS = [];

// LOCALIZATION
export const MESSAGES: Record<string, Record<string, string>> = {
    tr: {
        'loginFormTitle': 'GİRİŞ FORMU',
        'username': 'Kullanıcı Adı',
        'password': 'Şifre',
        'keepSignedIn': 'Oturumu açık tut',
        'forgotPassword': 'Şifremi unuttum',
        'loginBtn': 'GİRİŞ',
        'invalidPassword': 'Hatalı şifre.',
        'userNotFound': 'Kullanıcı bulunamadı.',
        'loggedInWelcome': 'Hoş geldiniz, {username}!',
        'loggedOut': 'Çıkış Yap',
        'newEmailReceived': 'Yeni bir e-posta aldınız: {subject}',
        'searchEmail': 'E-postalarda ara...',
        'inbox': 'Gelen Kutusu',
        'sent': 'Gönderilenler',
        'drafts': 'Taslaklar',
        'trash': 'Çöp Kutusu',
        'createEmail': 'Yeni E-posta Yaz',
        'reply': 'Yanıtla',
        'send': 'Gönder',
        'message': 'Mesaj',
        'dashboard': 'Panel',
        'customerList': 'Müşteri Listesi',
        'appointmentsTitle': 'Randevular',
        'tasks': 'Görevler',
        'expenses': 'Giderler',
        'interviewFormsTitle': 'Görüşme Formları',
        'offerManagement': 'Teklif Yönetimi',
        'manufacturing-analysis': 'İmalat Analizi',
        'reconciliation': 'Mutabakat',
        'emailHub': 'E-posta Merkezi',
        'emailDrafts': 'E-posta Taslakları',
        'aiHubTitle': 'Yapay Zeka Merkezi',
        'reports': 'Raporlar',
        'auditLog': 'Denetim Kaydı',
        'personnelManagement': 'Personel Yönetimi',
        'locationTracking': 'Konum Takip',
        'erpIntegration': 'ERP Entegrasyonu',
        'calculationTools': 'Hesaplama Araçları',
        'profileTitle': 'Profil',
        'aiSettings': 'AI Ayarları',
        'searchPlaceholder': 'Ara...',
        'noResultsFound': 'Sonuç bulunamadı.',
        'save': 'Kaydet',
        'cancel': 'İptal',
        'delete': 'Sil',
        'edit': 'Düzenle',
        'view': 'Görüntüle',
        'actions': 'İşlemler',
        'nameCompanyName': 'Adı / Firma Adı',
        'email': 'E-posta',
        'phone': 'Telefon',
        'status': 'Durum',
        'active': 'Aktif',
        'passive': 'Pasif',
        'notes': 'Notlar',
        'areYouSure': 'Emin misiniz?',
        'deleteConfirmation': 'Bu kaydı silmek istediğinizden emin misiniz?',
        'fieldsRequired': 'Gerekli alanları doldurun.',
        'genericError': 'Bir hata oluştu.',
        'permissionDenied': 'Bu işlem için yetkiniz bulunmuyor.',
        'adminPrivilegeRequired': 'Bu sayfaya erişmek için yönetici yetkisi gereklidir.',
        'recipient': 'Alıcı',
        'subject': 'Konu',
        'creationDate': 'Oluşturma Tarihi',
        'sentStatus': 'Gönderildi',
        'descriptionEnhanced': 'Açıklama AI ile iyileştirildi.',
        'aiError': 'Yapay zeka servisinde hata oluştu.',
        'markAllAsRead': 'Tümünü Okundu Say'
    },
    en: {
        'loginFormTitle': 'LOGIN FORM',
        'username': 'Username',
        'password': 'Password',
        'keepSignedIn': 'Keep me signed in',
        'forgotPassword': 'Forgot password',
        'loginBtn': 'LOGIN',
        'invalidPassword': 'Invalid password.',
        'userNotFound': 'User not found.',
        'loggedInWelcome': 'Welcome, {username}!',
        'loggedOut': 'Logout',
        'newEmailReceived': 'New email received: {subject}',
        'searchEmail': 'Search emails...',
        'inbox': 'Inbox',
        'sent': 'Sent',
        'drafts': 'Drafts',
        'trash': 'Trash',
        'createEmail': 'Compose Email',
        'reply': 'Reply',
        'send': 'Send',
        'message': 'Message',
        'dashboard': 'Dashboard',
        'customerList': 'Customers',
        'appointmentsTitle': 'Appointments',
        'tasks': 'Tasks',
        'expenses': 'Expenses',
        'interviewFormsTitle': 'Interview Forms',
        'offerManagement': 'Offers',
        'manufacturing-analysis': 'Mfg Analysis',
        'reconciliation': 'Reconciliation',
        'emailHub': 'Email Hub',
        'emailDrafts': 'Email Drafts',
        'aiHubTitle': 'AI Hub',
        'reports': 'Reports',
        'auditLog': 'Audit Log',
        'personnelManagement': 'Personnel',
        'locationTracking': 'Location Tracking',
        'erpIntegration': 'ERP Integration',
        'calculationTools': 'Calculation Tools',
        'profileTitle': 'Profile',
        'aiSettings': 'AI Settings',
        'searchPlaceholder': 'Search...',
        'noResultsFound': 'No results found.',
        'save': 'Save',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'edit': 'Edit',
        'view': 'View',
        'actions': 'Actions',
        'nameCompanyName': 'Name / Company Name',
        'email': 'Email',
        'phone': 'Phone',
        'status': 'Status',
        'active': 'Active',
        'passive': 'Passive',
        'notes': 'Notes',
        'areYouSure': 'Are you sure?',
        'deleteConfirmation': 'Are you sure you want to delete this record?',
        'fieldsRequired': 'Please fill in required fields.',
        'genericError': 'An error occurred.',
        'permissionDenied': 'You do not have permission for this action.',
        'adminPrivilegeRequired': 'Admin privilege is required to access this page.',
        'recipient': 'Recipient',
        'subject': 'Subject',
        'creationDate': 'Creation Date',
        'sentStatus': 'Sent',
        'descriptionEnhanced': 'Description enhanced by AI.',
        'aiError': 'AI Service Error.',
        'markAllAsRead': 'Mark all as read'
    }
};
